<h3>Editando Aluno</h3>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('escola-admin-interna', array('controller' => 'alunos', 'action' => 'edit')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'))."<br/>";
echo $this->formRow($form->get('curso')) . "<br/>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>