<h1>Alunos</h1>
<br/>
<p>
    <a href="<?php echo $this->url('escola-admin-interna', array('controller' => 'alunos', 'action' => 'new')); ?>">Novo</a> 
</p>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Curso</th>
        <th>Acao</th>
    </tr>
    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?php echo $entity->getId(); ?></td>
            <td><?php echo $entity->getNome(); ?></td>
            <td><?php echo $entity->getCurso(); ?></td>
            <td>
                <a href="<?php
                echo $this->url('escola-admin-interna', array('controller' => 'alunos', 'action' => 'edit', 'id' => $entity->getId()));
                ?>">Editar</a>
                <a href="<?php
                echo $this->url('escola-admin-interna', array('controller' => 'alunos', 'action' => 'delete', 'id' => $entity->getId()));
                ?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>
<br/>
<?php echo $this->paginationControl($this->data, 'Sliding', 'Paginator'); ?>