<h3>Login</h3>
<?php if ($this->error): ?>
    <p><b>Usuario ou senha Invalidos</b></p>
<?php endif; ?>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('escola-admin-auth'));
$form->prepare();
echo $this->form()->opentag($form);
echo $this->formRow($form->get('email')) . "<br/>";
echo $this->formRow($form->get('password')) . "<br/>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>