<!--<h1>Categorias</h1>
<br />

<ul>
    <?php // foreach ($this->categorias as $categoria): ?>
        <li><?php // echo $categoria; ?>

            <ul>
                <?php // foreach ($categoria->getLivros() as $livro): ?>
                    <li><?php // echo $livro->getNome(); ?></li>
                <?php // endforeach; ?>

            </ul>
        </li>
    <?php // endforeach; ?>
</ul>-->

<table border="1" style="margin: 5px;" class="table-striped">
    <tr>
    <?php foreach ($this->alunos as $aluno): ?>
        <li><?php echo $aluno; ?>

            <ul>
                <?php foreach ($aluno->getCursos() as $curso): ?>
                    <li><?php echo $curso->getNome(); ?></li>
                <?php endforeach; ?>
            </ul>
        </li>
    <?php endforeach; ?>
        <th>ID</th>
        <th>Nome</th>
        <th>Login</th>
        <th>curso</th>
        <th>Ação</th>
    </tr>
</table>