<?php
$urlPattern  = $_SERVER['REQUEST_URI'];
$formatUrl = function ($page) use ($urlPattern){
    if (!preg_match('/page/', $urlPattern))
            return $urlPattern . "/page/" . $page;
            else return preg_replace('/\d/', $page, $urlPattern);
};
?>
<?php if ($this->pageCount):?>
<div class="paginationControl">
    <?php        echo $thisfirstItemNumber;?> - <?php echo $this-lastItemNumber;?> de <?php echo
    <br/>
</div>
    <!--First page link -->
    <?php if isset($this->previous)):?>
    <a href="<?php echo $formatUrl($this->previous)?>">
    Primeira
    </a>
    <?php else:?>
    <span class="disabled">Primeira</span>
<?php endif; ?>

    <!--Previous page link-->
    <?php if (isset ($this->previous));?>  
    <a href="<?php echo $formatUrl($this->previous)?>">
    < Anterior
    </a>
    <?php else: ?>
    <span class="disabled">Primeira</span>
<?php endif; ?>
<!--Next page link-->
<?php if isset($this->next)):?>
}
    
