<h1>Cursos</h1>
<br/>
<p>
    <a href="<?php echo $this->url('escola-admin-interna',array('controller'=>'cursos','action'=>'new'));?>">Novo</a> 
</p>
<table class="table">
    <tr>
        <th>ID</th>
        <th>Nome</th>
        <th>Acao</th>
    </tr>
    <?php foreach ($this->data as $entity): ?>
        <tr>
            <td><?php echo $entity->getId(); ?></td>
            <td><?php echo $entity->getNome(); ?></td>
            <td>
                <a href="<?php echo $this->url('escola-admin-interna',
    array('controller' => 'cursos', 'action' => 'edit', 'id' => $entity->getId()));
    ?>">Editar</a>
                <a href="<?php echo $this->url('escola-admin-interna',
    array('controller' => 'cursos', 'action' => 'delete', 'id' => $entity->getId()));
    ?>">Deletar</a>
            </td>
        </tr>
    <?php endforeach; ?>

</table>
<br/>
<?php echo $this->paginationControl($this->data, 'Sliding', 'Paginator'); ?>