<h3>Novo user</h3>
<?php
$form = $this->form;
$form->setAttribute('action', $this->url('escola-admin', array('controller' => 'users', 'action' => 'new')));
$form->prepare();
echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('nome'))."<br/>";
echo $this->formRow($form->get('email'))."<br/>";
echo $this->formRow($form->get('password'))."<br/>";
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();
?>